### PR TITLE
Events for Drag Behavior

### PR DESCRIPTION
**Pull request by Enderthexen**
Changed the Drag Behavior to dispatch "dragstart" and "dragstop" events.

### CODE REVIEW

**Comment by stevenvergenz** [comment]
Everything looks good to me, but it's hard to know for sure without testing. Could you create an example that uses this?

**Comment by Enderthexen** [comment]
Yeah, I'd be happy to put a simple example together. Would you prefer that I comment a link to the example here or push another commit with the example?

**Comment by stevenvergenz** [comment]
Add it to the examples folder please :)

**Comment by Enderthexen** [comment]
Done!

**Comment by brianpeiris** [comment]
Made a few changes in #180:
- Added doc comments for the new events, so that they show up in our generated documentation
- Added the new example to the index.html file
- Removed the redundant (and somewhat misleading) `point` property from the events
- Simplified and cleaned up the example a bit

Thanks for the contribution!

**Pull request merged**
