### PR TITLE
Added HoverScale behavior and circle button example utilizing behavior

### PR DESCRIPTION
**Pull request by NGenesis**
Added HoverScale behavior:
Changes the scale of an object when the cursor hovers over it, and restores the original scale when the cursor is no longer hovering over the object.

Added circle button example:
Utilizes the HoverScale and HoverColor behaviors and cursor events to create an interactive component with visual feedback.

### CODE REVIEW

**Comment by Fasani** [comment]
Should you also update the docs?
http://altspacevr.github.io/AltspaceSDK/doc/module-altspace_utilities_behaviors.html

**Comment by NGenesis** [comment]
The docs should be updated automatically by the build process should the pull request be accepted.

**Comment by Fasani** [comment]
Ok good to know, thanks 👍

**Comment by brianpeiris** [comment]
Awesome! Thanks.

**Pull request merged**
