### PR TITLE
Update living room

### PR DESCRIPTION
**Pull request by amberroy**

### CODE REVIEW

**Comment by amberroy** [comment]
@brianpeiris pls review

**Comment by GavanWilhite** [comment]
Did you intend to change this file, or was it just a recompilation?

**Comment by brianpeiris** [comment]
Looks like there was a point release on babel that changed things slightly. It should be a safe change but did you mean to change actual code with this PR as well?

**Comment by brianpeiris** [comment]
We'll have to use exact version numbers for the babel packages in package.json to avoid this, or else it will get annoying with their point releases.

**Pull request merged**
