### PR TITLE
Merging gamejam branch

### PR DESCRIPTION
**Pull request by amberroy**
Adding ownership feature to Object3DSync behavior, enabled by keeping track of clientIds in SceneSync.

### CODE REVIEW

**Comment by GavanWilhite** [comment]
(hey, dunno if this is finished or not, but looks like the elemental docs
are still there, will want to re run doc gen)

**Comment by amberroy** [comment]
Good catch, I'd forgotten to run doc gen, done now.

**Comment by GavanWilhite** [comment]
Great, it's a little hard to see in the change log here, but were you able to look at the documentation comments from Brian?

**Comment by amberroy** [comment]
Added doc comments from Brian in PR https://github.com/AltspaceVR/AltspaceSDK/pull/105

**Comment by brianpeiris** [comment]
Avoid including generated docs in pull requests, it makes them impossible to review. The deploy script will take care of generating docs for releases going forward.

**Comment by amberroy** [comment]
Done, thanks for you feedback!  Re Object.keys ordering, I had the same question and looked it up, yes it will preserve insertion order for strings, which is not technically a standard but is the "de factor" standard on all browsers including Chrome.  In any case our code does not rely on a specific order, because although the master client is usually the one who's been in the room longest, we don't guarantee it (only that there will be exactly 1 master client per room).

**Pull request merged**
