### PR TITLE
Combine with aframe-altspace-component repo

### PR DESCRIPTION
**Pull request by stevenvergenz**
This is a big one! These are the most significant changes:

* Combined the AltspaceSDK and aframe-altspace-component repositories into one.
* Ported the entire SDK codebase to the new ECMAScript 2015 syntax.
* New package build system based on ES2015 modules.
* Reformatted, cleaned, and improved documentation for both APIs.
* All JS behaviors are now classes, so the `new` keyword is required when instantiating them. This is reflected in the examples.
* All A-Frame components are classes in addition to registered components. They are accessible through the `altspace.components` namespace. They are not usable in JS as-is, but might be useful for third parties to replicate the functionality.
* Updated the official Three.js version recommendation to r84.

### CODE REVIEW

**Comment by stevenvergenz** [comment]
Wow, github's diff is basically useless here. Not that surprising, but unfortunate. Any ideas for review?

**Comment by brianpeiris** [comment]
Testing notes:
- Multiloader seems to be broken, so some of the examples are affected: chess, solar system, hats
- The Bob behavior seems to have different defaults? The Bob motion is a lot more exaggerated
- HoverScale seems to have broken
- Aframe tests are missing from the tests/index.html file (though maybe we should split them out into examples/aframe/tests and examples/js/tests?)

**Comment by brianpeiris** [comment]
Remember to add in the release notes that this update will include official support for three.js r84

**Comment by brianpeiris** [comment]
We should have the gulp script build a separate aframe-altspace-component.js library before we release. Maybe call it aframe-altspace.js since it really consists of mulitple components

**Comment by brianpeiris** [comment]
Hmm, we'll have to talk about that. Not sure how versioning/tagging/deploying would work with multiple output libraries.

**Pull request merged**
