### PR TITLE
Fixing spelling mistakes and removing whitespace.

### PR DESCRIPTION
**Pull request by Fasani**
I tidied up a few spelling mistakes and changed altspace to Altspace where needed.

This commit is quite large as I also have a plugin that removes whitespace at the end of lines and my preference settings is for spaces over tabs.

If you do not want to accept the commit I can make the spelling fixes without the additional removal of whitespace etc.

Please just let me know.

### CODE REVIEW

**Comment by brianpeiris** [comment]
Thanks for the spelling fixes Fasani, but please use tabs, since that's our code style.

**Comment by Fasani** [comment]
I will fix them without any other changes, makes more sense.

**Comment by Fasani** [comment]
@brianpeiris ready for review.

**Comment by brianpeiris** [comment]
Awesome, looks good to me. Thank you!

**Pull request merged**
